name: Github Testing
on: [push]

permissions:
  contents: read
  id-token: write

jobs:
  bundle_audit:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      - name: config bundler
        run: |
          bundle config set without 'development staging production'
          bundle config set deployment 'true'
          bundle env
          head -n1 $(which bundle)
      - name: Install bundle-audit
        run: gem install bundle-audit
      - name: Bundle Audit Check
        run: bundle exec bundle-audit check --update

  brakeman:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      - name: config bundler
        run: |
          bundle config set without 'development staging production'
          bundle config set deployment 'true'
          bundle env
          head -n1 $(which bundle)
      - name: Install brakeman
        run: gem install brakeman
      - name: Run Brakeman
        run: bundle exec brakeman --quiet --skip-libs --exit-on-warn --ignore-config=.brakeman-ignore

  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
        ruby: ['3.2.2']
    runs-on: ${{ matrix.os }}
    env:
      RAILS_ENV: test
      COVERAGE: true
      DISABLE_SPRING: 1

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: config bundler
        run: |
          bundle config set without 'development staging production'
          bundle config set deployment 'true'
          bundle env
          head -n1 $(which bundle)

      - name: Install dependencies
        run: |
          gem install bundler -v '>= 2.2.10'
          gem install builder
          gem install nokogiri -v '~> 1.11.3'
          gem install savon
          gem install webmock
          gem install mocha
          gem install minitest -v '~> 5.14'
          gem install simplecov -v '<= 0.17.1'
          bundle install

      - name: Run Tests
        run: rake

      - name: Setup qlty.sh
        run: |
          curl -sSL https://qlty.sh/install.sh | bash
          qlty --version

      - name: Run qlty.sh analysis
        run: |
          qlty analyze --format json --output qlty-report.json

      - name: Upload coverage to qlty.sh
        uses: qltysh/qlty-action/coverage@v1
        with:
          oidc: true
          files: coverage/.resultset.json

      - uses: actions/upload-artifact@v4
        with:
          name: qlty-report-${{ matrix.ruby }}
          path: qlty-report.json

      - uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.ruby }}
          path: coverage/
